### PR TITLE
update fbneo

### PR DESCRIPTION
**Pull request by raidenii**

### CODE REVIEW

**Comment by christianhaitian** [comment]
So it compiled with cyclone without issue on your end?

**Comment by raidenii** [comment]
@christianhaitian Correct. I'm using Void Linux on WSL to compile though, so not sure if it's dependency issue on your end failed it. If you wish, I can post a compile log along with the build patches I have.

**Comment by christianhaitian** [comment]
Yes, please do and much appreciated.

**Comment by raidenii** [comment]
Template:
```[user@user-Desktop xcompile]$ cat srcpkgs/fbneo-libretro/template
# Template file for 'fbneo-libretro'
pkgname=fbneo-libretro
version=1.0.0.3
revision=2
wrksrc="fbneo-master"
hostmakedepends="pkg-config libtool git"
makedepends="zlib-devel libdrm-devel libgomp-devel MesaLib-devel"
short_desc="${pkgname}"
license="GPL-2.0-only"
homepage="https://github.com/libretro/FBNeo"
patch_args="-Np1"

do_fetch() {
    git clone ${homepage}.git ${wrksrc}
    cd ${wrksrc}
}

do_build() {
    case "$XBPS_TARGET_MACHINE" in
        aarch64*) _platform="goadvance";;
    esac

    make -j16 -C src/burner/libretro profile=performance
}

do_install() {
    vinstall "${pkgname}.so" 755 opt/libretro
}
```

Patch for makefile:
```[user@user-Desktop xcompile]$ cat srcpkgs/fbneo-libretro/patches/build.patch
diff --git a/src/burner/libretro/Makefile b/src/burner/libretro/Makefile
index 0ee72599..69402efb 100644
--- a/src/burner/libretro/Makefile
+++ b/src/burner/libretro/Makefile
@@ -359,2 +359,16 @@

+else ifeq ($(platform), goadvance)
+        TARGET := $(TARGET_NAME)_libretro.so
+        fpic := -fPIC
+        SHARED := -shared -Wl,-no-undefined -Wl,--version-script=$(VERSION_SCRIPT)
+        PLATFORM_FLAGS = -march=armv8-a+crc+fp+simd -mcpu=cortex-a35 -Ofast -frename-registers -ftree-vectorize
+        USE_EXPERIMENTAL_FLAGS = 1
+        USE_CYCLONE = 1
+        ARCH = arm64
+        ENDIANNESS_DEFINES := -DLSB_FIRST
+        LDFLAGS += -static-libgcc -static-libstdc++
+        CFLAGS += $(PLATFORM_FLAGS)
+        CXXFLAGS += $(PLATFORM_FLAGS)
+#######################################
+
 # Nintendo Game Cube / Wii / WiiU
```

**Comment by raidenii** [comment]
Build log:
[fbneo-libretro-build.log](https://github.com/christianhaitian/retroarch-cores/files/6951611/fbneo-libretro-build.log)

**Comment by christianhaitian** [comment]
Finally had a chance to check this out and I don't see evidence in the build log that cyclone is enabled.  I even checked to see if it's possible to enable cyclone from the core options menu while a game is loaded and there's no option there to enable cyclone using the latest fbneo core you built.  Am I missing something?

**Pull request merged**
